services:
  - type: web
    name: useragent-generator
    env: python
    region: ohio
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000